apiVersion: apps/v1
kind: Deployment
metadata:
  name: empsyappdeployment
spec:
  selector:
    matchLabels:
      app: empsyapp
  replicas: 3
  template:
    metadata:
      labels:
        app: empsyapp
    spec:
      containers:
        - name: empsyapp
          image: sid2703/empapprepository:1
          ports:
            - containerPort: 8080
        

---

apiVersion: v1 
kind: Service 
metadata: 
  name: empsyappservice
spec:
  selector:
    app: empsyapp
  ports:
    - protocol: "TCP"
      port: 8080 
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.

