spring:
 datasource:
  url: jdbc:sqlserver://databasesid.database.windows.net:1433;database=Sid;user=Sid@databasesid;password={Pass@123};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: Sid
  password: Pass@123
 jpa:
  show-sql: true
  hibernate:
   ddl-auto: update
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   
server:
 port: 8080
